---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/hours
  label: Öppettider
  create: documents
  match: "**/*"
  new_doc_ext: ".json"
  templates:
  - oppettid
- type: heading
  label: Öppettider
- type: heading
  label: Content
- type: directory
  path: content/employees
  label: Employees
  create: documents
  match: "**/*"
  templates:
  - employee
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
